### ISSUE TITLE
Building Sylvan 1.1.2 on MacOS fails

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/sylvan#14]
ld: library not found for -largp

**Comment by alaarman** [comment]
Standard FLAGS environment variables seem to be ignored, so I am guessing they are overwritten in CMakeFiles somewhere
make LDFLAGS="-L/opt/local/lib"  <-- ignored

**Comment by Meijuh** [comment]
What about the latest 1.4.0? I see that this doesn't help of course for LTSmin 3.0.0, because it requires < 1.2. So maybe we can backport and release 1.1.3.

**Comment by alaarman** [comment]
Or is it easier to support 1.4.0 in LTSmin 3.0.0?

It was anyway rather tedious to retrieve version 1.1.2 (nowhere was it written that this was the upper bound of the LTSmin-3 compatible versions).

**Comment by alaarman** [comment]
@trolando ?

**Comment by Meijuh** [comment]
@alaarman it is written in the readme:
```
Optional Dependencies
Sylvan
To build the parallel symbolic algorithms, Sylvan (>=1.1, < 1.2) is required. If Sylvan is installed in a non-standard location please refer to this note on aclocal and pkgconf, and this note on configuring pkgconf.
```
An online version is here: http://jmeijer.nl/ltsmin/#sylvan.
It is hard to find though, because LTSmin should really be released. Then this information can be found at ltsmin.utwente.nl I really don't want to add support for Sylvan 1.4 right now in 3.0.0. Somebody else can do it, but it needs to been soon and well tested.

**Comment by alaarman** [comment]
I know. But retrieving that version is not easy at least for me (you decide hat that means ;)). I basically guessed a tag as I didn't automatically get a list. On github it is also hard to retrieve the list of tags.
We could at least change the constraint to <= 1.1.2 and place a link to that version.

Nice website btw.

**Comment by Meijuh** [comment]
It is here https://github.com/utwente-fmt/sylvan/releases, right? You don't have to build from a git repo, you could just download and build the 1.1.2 sources.

> Nice website btw.

:)

**Comment by trolando** [comment]
No longer applicable as the newest version of LTSmin works with newer versions of Sylvan.
